apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-log4j-app
  labels:
    app: vulnerable-log4j-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-log4j-app
  template:
    metadata:
      labels:
        app: vulnerable-log4j-app
    spec:
      hostNetwork: true
      containers:
      - name: vulnerable-log4j-app
        image: quay.io/vicenteherrera/log4shell-vulnerable-app
        ports:
        - containerPort: 8080
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: In
                    values:
                      - "k8s-worker-2"
    
---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-log4j
spec:
  type: NodePort
  selector:
    app: vulnerable-log4j-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31001
# # ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: rogue-jndi-app
#   labels:
#     app: rogue-jndi-app
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: rogue-jndi-app
#   template:
#     metadata:
#       labels:
#         app: rogue-jndi-app
#     spec:
#       containers:
#       - name: rogue-jndi-app
#         image: quay.io/vicenteherrera/rogue-jndi
#         imagePullPolicy : Always
#         ports:
#         - containerPort: 1389
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: rogue-jndi
# spec:
#   type: NodePort
#   selector:
#     app: rogue-jndi-app
#   ports:
#     - protocol: TCP
#       port: 1389
#       targetPort: 1389